
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "../../../modules//manifest"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

# Wire the name unit's output in. The mocks let validate/plan run before `name` has ever
# been applied (run --all plan on a fresh checkout); apply always uses the real output.
dependency "name" {
  config_path = "../name"

  mock_outputs = {
    unique_name = "mock-name-00000000"
  }
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Name the manifest describes (from the name unit).
  # Type: string
  name = dependency.name.outputs.unique_name

  # environment: from root.hcl (the nearest env.hcl)


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Tags written into the manifest.
  # Type: map
  # tags: from root.hcl

}
